# 基础设置
#-------------------------------------------------------------------
baseURL = "https://lsygod.github.io/"               # 博客部署网址
title = "JOJO's Blog"                              # 网站名称
enableRobotsTXT = true                         # 是否支持Robots协议
enableEmoji = true                             # 是否支持Emoji表情符号
theme = "jane"                                 # 选用jane主题
hasCJKLanguage = true                          # 自动检测是否包含 中文\日文\韩文
paginate = 10                                  # 首页每页显示的文章数目
rssLimit = 20                                  # 限制 Rss 文章输出数量
disqusShortname = ""                           # disqus_shortname
googleAnalytics = ""                           # 配置google统计
copyright = ""                                 # 默认为下面配置的author.name，

# 关于语言
defaultContentLanguage = "zh-cn"               # 默认博客语言环境
[languages.zh-cn]                              # 语言支持
  languageCode = "zh-cn"

# 关于语法高亮，具体使用可查看https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true                      # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true                      # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true           #
PygmentsOptions = "linenos=table"              # 开启显示行号

[author]                                       # 作者名称
  name = "BookeenGao"

[sitemap]                                      # 站点地图
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
#-------------------------------------------------------------------

#菜单设置
#-------------------------------------------------------------------
[[menu.main]]
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "分类"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "标签"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Github"
  weight = 70
  url = "https://github.com/lsygod"
#-------------------------------------------------------------------

#其他参数设置
#-------------------------------------------------------------------
[params]
  since = "2022"                                # 站点建立时间
  homeFullContent = false                       # 主页是否显示全部文章内容
  rssFullContent = true                         # if false, Rss feed instead of the summary
  logoTitle = "JOJO"                         # 博客标题，默认值是上面设置的title，也就是网址名称
  keywords = ["Hugo", "go", "后端"]  # 关键字
  description = "后端搬砖记录"                              # 网页描述
  archive-paginate = 30                         # 归档、标签、分类每页显示的文章数目
  dateFormatToUse = "2006-01-02"                # 日期显示格式，查看可支持的格式见https://gohugo.io/functions/format/
  moreMeta = true                               # 是否显示字数统计与阅读时间
  showMenuLanguageChooser = true                # 显示语言选择开关
  showAuthorInfo = true                         # 文章末尾显示作者信息

  # 一些全局开关，这些是默认值，也可以在每一篇内容的 front matter 中对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  toc = true                                    # 是否开启目录
  photoswipe = true                             # 是否启用PhotoSwipe（图片可点击）
  bootcdn = true                                # 是否使用bootcdn
  mathjax = false                               # 是否使用mathjax（数学公式）
  contentCopyright = 'BookeenGao' # 版权声明

  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file
#-------------------------------------------------------------------

# CDN设置
#-------------------------------------------------------------------
  [params.publicCDN]        # load these files from public cdn
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
    photoswipe = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.js" integrity="sha256-AC9ChpELidrhGHX23ZU53vmRdz3FhKaN9E28+BbcWBw=" crossorigin="anonymous"></script>'
    photoswipeUI = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js" integrity="sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=" crossorigin="anonymous"></script>'
    photoswipeCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.css" integrity="sha256-SBLU4vv6CA6lHsZ1XyTdhyjJxCjPif/TRkjnsyGAGnE=" crossorigin="anonymous">'
    photoswipeSKIN = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.css" integrity="sha256-c0uckgykQ9v5k+IqViZOZKc47Jn7KQil4/MP3ySA3F8=" crossorigin="anonymous">'
#-------------------------------------------------------------------

# 下面是关于评论系统，更新显示commit内容，谷歌搜索，文章打赏，访问数据统计等等
#-------------------------------------------------------------------
  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "lsygod/comment"    # The repo to store comments
    issueTerm = "pathname"

  [params.livere]               #LiveRe comment. see https://www.livere.com/
    uid = ""

  [params.counter.busuanzi]  # a Chinese visitor counter  # 卜算子计数器
    enable = false

  [params.counter.leancloud]  # Chinese leancloud visitor counter  # leancloud 计数器
    enable = false
    appId = ""
    appKey = ""

  [params.commentCount.disqus] # show counts of comments for Disqus
    enable = false

  [params.social]                                         # 社交链接
    a-email = ""
    g-github = "https://github.com/lsygod"